print("BASKETBALL TRACKER")
player_name = input("Enter player name: ")
points_scored = input("Enter points scored: ")
rebounds = input("Enter rebounds: ")
assists = input("Enter assists: ")
print("Player Name: ", player_name)
print("Points Scored: ", points_scored)
print("Rebounds: ", rebounds)
print("Assists: ", assists)

